config/routes.rb
Rails.application.routes.draw do
  root 'memos#index'
  resources :memos do
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users
  
  
  

  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :memo
  
  validates :content, presence: true, length: {minimum: 2, maximum: 200}
  validates :user_id, presence: true
  validates :memo_id, presence: true
  
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :content, presence: true, length: { minimum: 2, maximum: 1000 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :memos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]
  before_action :is_owner?, only: [:destroy]
  
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to memo_path(params[:memo_id])
  end
  
  def destroy
    @comment.destroy
    redirect_to :back
  end
  
  private
  def set_comment
    @comment = Comment.find(params[:id])
  end
  
  def comment_params
    params.require(:comment).permit(:content, :user_id, :memo_id)
  end
  
  def is_owner?
    redirect_to root_path unless current_user == @comment.user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  before_action :is_owner?, only: [:edit, :update, :destroy]
# Create
  def new
    @memo = Memo.new
  end
  
  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to @memo
    else
      render :new
    end
  end
  
# Read
  def show
    @comment = Comment.new
    @comments = @memo.comments
  end

  def index
    # binding.pry
    @memos = Memo.order(created_at: :DESC).page(params[:page]).per(10)
  end
  
# Update
  def edit
    unless current_user == @memo.user
      redirect_to @memo
    end
  end
  
  def update
    if @memo.update(memo_params)
      redirect_to @memo
    else
      render :edit
    end
  end
  
# Destroy
  def destroy
    @memo.destroy!
    redirect_to root_path
  end
  
  private
  def set_memo
    @memo = Memo.find(params[:id])
  end
  
  def memo_params
    params.require(:memo).permit(:title, :content, :user_id)
  end
  
  def is_owner?
    redirect_to root_path unless current_user == @memo.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
  def icon name
    content_tag(:span, '', class: ['glyphicon', "glyphicon-#{name}"])
  end
end

app/views/home/index.html.erb
<h1>Hack Your Memo</h1>
<p>Memo app!</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Memo app', root_path, id: 'logo'%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Neo Memo', new_memo_path %></li>
        <% if user_signed_in? #로그인을 했으면? %>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else #로그인을 안했으면 %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memo app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: ["alert", "alert-#{message_type}"]) %>
  <% end %>
  <%= yield %>
</div>
<%= console if Rails.env.development? %>
</body>
</html>

app/views/memos/_form.html.erb
<%= bootstrap_form_for @memo do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id  %> 
  <%= f.text_field :title, label: '제목' %>
  <%= f.text_area :content, label: 'Memo', class: "tinymce", rows: 15, cols: 120 %>
  <%= tinymce %>
  <%= f.submit %>
<% end %>

app/views/memos/edit.html.erb
<h1>edit memo</h1>
<hr />

<%= render 'form' %>

app/views/memos/index.html.erb
<h1>Hack Your Memo</h1>
<div class="table-responsive">
  <table class="table table-fit">
    <thead>
      <tr>
        <th>title</th>
        <th>user</th>
        <th>comments</th>
      </tr>
    </thead>
    <tbody>
      <% @memos.each do |memo| %>
        <tr>
          <td><%= link_to memo.title, memo %></td>
          <td><%= memo.user.email %></td>
          <td><%= memo.comments.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @memos %>
</div>


    

app/views/memos/new.html.erb
<h1>neo memo</h1>
<hr />

<%= render 'form' %>

app/views/memos/show.html.erb
<h1><%= @memo.title %></h1>
<hr />
<h2>by <%= @memo.user.email %></h2>
<h3><%= icon 'time' %><%= local_time(@memo.created_at) %></h3>
<% if current_user == @memo.user %>
  <%= icon 'pencil' %><%= link_to '수정하기', edit_memo_path(@memo) %> | 
  <%= icon 'trash' %><%= link_to '삭제하기', memo_path, method: :delete %>
<% end %>
<hr />
    <%= @memo.content.html_safe %>
<hr />

<div class="well">
  <% if user_signed_in? %>
    <%= bootstrap_form_for @comment, url: memo_comments_path(@memo) do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :memo_id, value: @memo.id %>
      <%= f.text_field :content, label: 'Leave a comment!' %>
      <%= f.submit %>
    <% end %>
  <% else %>
    <%= link_to '댓글을 남기려면 로그인 하세요!', new_user_session_path	%>
  <% end %>
</div>

<hr />

<% @comments.each do |comment| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <strong><%= comment.user.email %></strong>
        <%= icon 'time' %>
        <small><%= local_time(comment.created_at) %></small>
        <% if current_user == comment.user %>
          <%= link_to icon('trash'), memo_comment_path(@memo, comment), method: :delete %>
        <% end %>
      </h4>
      <%= comment.content %>
    </div>
  </div>
  <hr />
<% end %>